# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aec5d7f281f37c91c199be9b6eb552f37eef56fbd11566f0fe7223a9c4fef0f90c758792ae27983f0a7942cfe1779a5f7006c1bf8792c50866bcbc9e4b827249

test:
  secret_key_base: 831ba07d839520b471fd96e560ac7575468db62d3e2e060f4a6d290d3e5a6b4a707d1a6572ac6676d88f33eef2755fefb772d08eeec175365d53ce221ae006de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
